export const resources = {
  en: {
    //Settings
    settingTitle: "Settings",
    version: "Version",
    userName: "User Name",
    userNum: "User Number",
    systemInfo: "System Information",
    language: "Language",
    storage: "Storage",
    storeDownload: "Download",
    items: "Items",
    changeSettings: "Change Settings",
    printerSettings: "Printer Settings",
    printTitle: "Title",
    printAddress: "Address",
    serveicExpair: "Serveic Expair",
    timeLeft: " Time Left",
    enterCode: "Enter Code",
    mode: "Mode",
    filterSettings: "Filter Settings",
    Item: "Item ",
    Price: "Price",
    Discount: "Discount",
    quantity: "Quantity",
    search: "Search",
    new: "New",
    save: "Save",
    //Dashboard
    dashbaordTitle: "Dashboard",
    mostActive: "Most Active Workers",
    statistics: "Statistics",
    numberofSoldRecord: "Number Of Sold Record",
    total: "Total Incom",
    newRecord: "New Record",
    //Records
    recordsTitle: "Records",
    import: "Import",
    export: "Export",
    filter: "Filter",
    worker: "worker",
    previous: "Previous",
    template: "Template",
    chooseTemplate: "Choose Template",
    buildRecord: "Build Record",
    customerName: "Customer Name",

    submit: "Submit",
    next: "Next",
    //record List
    createDate: "Create Date",
    description: "Descrition",
    residual: "Residual",
    received: "Received",
    discount: "Discount",
    creater: "Creater",
    customer: "Customer Name ",
    editDate: "Edit Date",
    //new records
    templateName: "Template Name",
    numberOfItems: "Number of Items",
    editDate: "Edit Date",
    createdBy: "Created by",
    driverName: "Driver Name",
    fullName: "Full Name",
    note: "Notes",
    newRecord: "New Record",
    //Workers
    workerTitle: "Workers",
    name: "Name",
    email: "Email",
    phone: "Phone",
    state: "State",
    address: "Address",
    addNewWorker: "Add new worker",
    //Admin
    adminsTitle: "Admins",
    addNewAdmin: "Add new admin",
    //Statistics
    statistics: "Statistics",
    income: "Incom",
    expanse: "Expanse",
    //pagination
    viewSearch: "View search of",
    from: "from",
    searchResulit: "search we got",
    //login
    password: "Password",
    username: "User Name",
    login: "Login",
    rememberme: "Remeber me",
    forgotpassword: "Forgot password ?",
    systemby: "A system by ",
    emptyFeild: "Empty feild",
  },
  ar: {
    //Settings
    settingTitle: "الاعدادت",
    version: "النسخة",
    userName: "اسم المستخدم",
    userNum: "رقم المستخدم",
    systemInfo: "معلومات النظام",
    language: "اللغة",
    storage: "المخزن",
    storeDownload: "تحميل",
    items: "عنصر",
    changeSettings: "تغير الاعدادت",
    printerSettings: "اعدادات الطباعة",
    printTitle: "عنوان",
    printAddress: "عنوان /نقطة دالة ",
    serveicExpair: "تارخ انتهاء الصلاحية",
    timeLeft: " الوقت المتبقي",
    enterCode: "ادخل الرمز",
    mode: "المظهر",
    filterSettings: "اعدادات البحث",
    Item: " العنصر",
    Price: "السعر",
    Discount: "الخصم",
    quantity: "الكمية",
    search: "بحث",
    new: "جديد",
    save: "حفظ",
    //Dashboard
    dashbaordTitle: "لوحة التحكم",
    mostActive: "اكثر العمال نشاطأ",
    statistics: "الاحصائيات",
    numberofSoldRecord: " عدد القوائم المباعة",
    total: "اجمالي الدخل",
    newRecord: "قائمة جديدة",
    //Records
    recordsTitle: "القوائم",
    import: "سحب",
    export: "استخراج",
    //record List

    createDate: "تاريخ الانشساء",
    description: "ملاحظات",
    residual: "المتبقي",
    received: "المستلم",
    discount: "الخصم",
    employe: "الموظف",
    filter: "بحث",
    creater: "المجهز",
    customer: " الزبون",
    editDate: "تاريخ التعديل",
    //new records
    templateName: "اسم القالب",
    numberOfItems: "عدد العناصر",
    editDate: "تاريخ التعديل",
    createdBy: "بواسطة",
    newRecord: "انشاء قائمة",
    worker: "عامل",
    driverName: "اسم السائق",
    fullName: " الاسم كامل",
    note: "ملاحظات",
    customerInfo: "معلومات الزبون",
    //Workers
    workerTitle: "العمال",
    name: " الاسم",
    email: "ايميل",
    phone: "هاتف",
    state: "الحالة",
    previous: "السابق",
    template: "قالب",
    chooseTemplate: "اختر القالب",
    buildRecord: "انشاء قائمة",
    submit: "تسليم",
    next: "التالي",
    address: "العنوان",

    addNewWorker: "اضاقة عامل جديد",
    //Admin
    adminsTitle: "المسؤولين",
    addNewAdmin: "اضافة مسؤول جديد", //Statistics
    statistics: "الاحصائيات",
    income: "اجمالي الدخل",
    expanse: "اجمالي المصروفات",
    //pagination
    viewSearch: "عرض ",
    from: "من",
    searchResulit: "نتائج البحث",
    //login
    password: "كلمة السر",
    username: "اسم المستخدم",
    login: "تسجيل دخول",
    rememberme: "تذكرني",
    forgotpassword: "نسيت الباسورد ؟ ",
    systemby: "نفذ بواسطة",
    emptyFeild: "حقل فارغ",
  },
};
