export const resources = {
  en: {
    //Settings
    settingTitle: "Settings",
    version: "Version",
    userName: "User Name",
    userNum: "User Number",
    systemInfo: "System Information",
    language: "Language",
    storage: "Storage",
    storeDownload: "Download",
    items: "Items",
    changeSettings: "Change Settings",
    printerSettings: "Printer Settings",
    printTitle: "Title",
    printAddress: "Address",
    serveicExpair: "Serveic Expair",
    timeLeft: " Time Left",
    enterCode: "Enter Code",
    mode: "Mode",
    filterSettings: "Filter Settings",
    Item: "Item ",
    Price: "Price",
    Discount: "Discount",
    quantity: "Quantity",
    search: "Search",
    new: "New",
    //Dashboard
    dashbaordTitle: "Dashboard",
    mostActive: "Most Active Workers",
    statistics: "Statistics",
    numberofSoldRecord: "Number Of Sold Record",
    total: "Total Incom",
    newRecord: "New Record",
    //Records
    recordsTitle: "Records",
    import: "Import",
    export: "Export",
    filter: "Filter",
    worker: "worker",
    //Workers
    workerTitle: "Workers",
    //Admin
    adminsTitle: "Admins",
    //Statistics
    statistics: "Statistics",
    income: "Incom",
    expanse: "Expanse",
    //pagination
    viewSearch: "View search of",
    from: "from",
    searchResulit: "search we got",
  },
  ar: {
    //Settings
    settingTitle: "الاعدادت",
    version: "النسخة",
    userName: "اسم المستخدم",
    userNum: "رقم المستخدم",
    systemInfo: "معلومات النظام",
    language: "اللغة",
    storage: "المخزن",
    storeDownload: "تحميل",
    items: "عنصر",
    changeSettings: "تغير الاعدادت",
    printerSettings: "اعدادات الطباعة",
    printTitle: "عنوان",
    printAddress: "عنوان /نقطة دالة ",
    serveicExpair: "تارخ انتهاء الصلاحية",
    timeLeft: " الوقت المتبقي",
    enterCode: "ادخل الرمز",
    mode: "المظهر",
    filterSettings: "اعدادات البحث",
    Item: " العنصر",
    Price: "السعر",
    Discount: "الخصم",
    quantity: "الكمية",
    search: "بحث",
    new: "جديد",
    //Dashboard
    dashbaordTitle: "لوحة التحكم",
    mostActive: "اكثر العمال نشاطأ",
    statistics: "الاحصائيات",
    numberofSoldRecord: " عدد القوائم المباعة",
    total: "اجمالي الدخل",
    newRecord: "قائمة جديدة",
    //Records
    recordsTitle: "القوائم",
    import: "سحب",
    export: "استخراج",
    filter: "بحث",
    worker: "worker",
    //Workers
    workerTitle: "العمال",
    //Admin
    adminsTitle: "المسؤولين",
    //Statistics
    statistics: "الاحصائيات",
    income: "اجمالي الدخل",
    expanse: "اجمالي المصروفات",
    //pagination
    viewSearch: "عرض ",
    from: "من",
    searchResulit: "نتائج البحث",
  },
};
